server:
  port: 8090
logging:
  level:
    root: DEBUG
    com.neo.app.controller: DEBUG
    org.springframework.web: DEBUG
    org.apache.tomcat: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.data: DEBUG
    org.springframework.boot.autoconfigure.web: TRACE

keycloak:
  url: http://localhost:8082
  realm: Neo_TM

spring:
  data:
    mongodb:
      database: Neo_TM_DB
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/donnes_authentifications

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB

  security:
    filter-dispatcher-types: async, error, request


