server:
  port: 8090
logging:
  level:
    org.springframework.web: DEBUG
    org.apache.tomcat: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.data: DEBUG
    org.springframework.boot.autoconfigure.web: TRACE
keycloak:
  url: http://localhost:8082
  realm: Neo_TM

spring:
  data:
    mongodb:
      database: Neo_TM_DB
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/donnes_authentifications

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB
  security:
    filter-dispatcher-types: async, error, request
    oauth2:
      client:
        registration:
          backend:
            client-id: Neo_TM_Backend
            client-secret: PjhDYxdsJ9c1WSwqG2yEphNyDSKEpepl
            provider: keycloak
            scope: openid, profile, email
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${keycloak.url}/realms/${keycloak.realm}
            token-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/auth
            user-info-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs


