server:
  port: 8090

logging:
  level:
    root: DEBUG
    com.neo.app.controller: DEBUG
    org.springframework.web: DEBUG
    org.apache.tomcat: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.data: DEBUG
    org.springframework.boot.autoconfigure.web: TRACE

keycloak:
  url: http://localhost:8082
  realm: Neo_TM

spring:
  data:
    mongodb:
      database: Neo_TM_DB
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/donnes_authentifications

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB

  security:
    filter-dispatcher-types: async, error, request
    oauth2:
      client:
        registration:
          backend:
            client-id: Neo_TM_Backend
            client-secret: Xo2z8VwYHXWUtgHBNwHJoVA9ICybNG78
            provider: keycloak
            scope: openid, profile, email
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/Neo_TM
            token-uri: http://localhost:8082/realms/Neo_TM/protocol/openid-connect/token
            authorization-uri: http://localhost:8082/realms/Neo_TM/protocol/openid-connect/auth
            user-info-uri: http://localhost:8082/realms/Neo_TM/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8082/realms/Neo_TM/protocol/openid-connect/certs

  mail:
    host: smtp.gmail.com
    port: 587
    username: grayen274@gmail.com
    password: rayen123 # ← ⚠️ ici colle le mot de passe d'application Gmail
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

app:
  company:
    name: Neolons
    support-email: support@neolons.com
  license:
    notification:
      enabled: true
    reminder:
      days: 7,3,1
